CREATE DATABASE IF NOT EXISTS lugus_library DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lugus_library;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) DEFAULT NULL,
    password VARCHAR(64) NOT NULL,
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    avatar VARCHAR(500) DEFAULT NULL,
    banner VARCHAR(500) DEFAULT NULL,
    blocked TINYINT(1) DEFAULT 0,
    block_reason VARCHAR(500) DEFAULT NULL,
    block_until DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(255) NOT NULL,
    info TEXT,
    filename VARCHAR(500) NOT NULL,
    uploaded_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(255) DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR(500) DEFAULT NULL AFTER role;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner VARCHAR(500) DEFAULT NULL AFTER avatar;
ALTER TABLE users ADD COLUMN IF NOT EXISTS blocked TINYINT(1) DEFAULT 0 AFTER banner;
ALTER TABLE users ADD COLUMN IF NOT EXISTS block_reason VARCHAR(500) DEFAULT NULL AFTER blocked;
ALTER TABLE users ADD COLUMN IF NOT EXISTS block_until DATETIME DEFAULT NULL AFTER block_reason;

INSERT IGNORE INTO users (email, password, role)
VALUES ('admin@lugus.com', SHA2('admin123', 256), 'admin');
